## Fake News Classifier Using LSTM

Dataset: https://www.kaggle.com/c/fake-news/data#

In [1]:
import pandas as pd

In [2]:
pip install -q kaggle

In [3]:
df = pd.read_csv('/content/train.csv', escapechar='\\', on_bad_lines='skip')

In [4]:
df.head()

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1

In [46]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [47]:
df.shape

(20799, 5)

In [48]:
df.head()

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1

In [27]:
df.isnull().sum()

;title;text;label    0
dtype: int64

In [49]:
###Drop Nan Values
df=df.dropna()

In [50]:
df.head()

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1

In [8]:
## Get the Independent Features

X=df.drop('label',axis=1)
X.head()

,id,title,author,text
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ..."
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...

In [30]:
## Get the Dependent features
y=df['label']

In [31]:
X.shape

(20799, 4)

In [32]:
y.shape

(20799,)

In [33]:
df.head()

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1

In [56]:
import tensorflow as tf

In [57]:
tf.__version__

'2.18.0'

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [12]:
### Vocabulary size
voc_size=5000

### Onehot Representation

In [13]:
messages=X.copy()

In [14]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [15]:
messages

,id,title,author,text
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ..."
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...
...,...,...,...,...
20794,20795,Rapper T.I.: Trump a ’Poster Child For White S...,Jerome Hudson,Rapper T. I. unloaded on black celebrities who...
20795,20796,"N.F.L. Playoffs: Schedule, Matchups and Odds -...",Benjamin Hoffman,When the Green Bay Packers lost to the Washing...
20796,20797,Macy’s Is Said to Receive Takeover Approach by...,Michael J. de la Merced and Rachel Abrams,The Macy’s of today grew from the union of sev...
20797,20798,"NATO, Russia To Hold Parallel Exercises In Bal...",Alex Ansary,"NATO, Russia To Hold Parallel Exercises In Bal..."
20798,20799,What Keeps the F-35 Alive,David Swanson,"David Swanson is an author, activist, journa..."

In [16]:
#messages.reset_index(inplace=True)

In [17]:
messages

,id,title,author,text
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ..."
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...
...,...,...,...,...
20794,20795,Rapper T.I.: Trump a ’Poster Child For White S...,Jerome Hudson,Rapper T. I. unloaded on black celebrities who...
20795,20796,"N.F.L. Playoffs: Schedule, Matchups and Odds -...",Benjamin Hoffman,When the Green Bay Packers lost to the Washing...
20796,20797,Macy’s Is Said to Receive Takeover Approach by...,Michael J. de la Merced and Rachel Abrams,The Macy’s of today grew from the union of sev...
20797,20798,"NATO, Russia To Hold Parallel Exercises In Bal...",Alex Ansary,"NATO, Russia To Hold Parallel Exercises In Bal..."
20798,20799,What Keeps the F-35 Alive,David Swanson,"David Swanson is an author, activist, journa..."

In [18]:
import nltk
import re
from nltk.corpus import stopwords

In [19]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [20]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

TypeError: expected string or bytes-like object, got 'float'

In [ ]:
corpus

In [21]:
corpus[0]

'hous dem aid even see comey letter jason chaffetz tweet'

In [22]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[4444, 4285, 4822, 4189, 384, 225, 2944, 1039, 3515, 79],
 [728, 401, 3380, 1042, 2583, 3419, 2837],
 [4787, 2360, 3686, 1030],
 [2568, 1690, 3545, 2054, 1369, 4313],
 [243, 2583, 1097, 3846, 759, 4214, 2583, 4396, 4420, 3144],
 [26,
  2119,
  179,
  3747,
  3358,
  2294,
  2069,
  1442,
  1275,
  1849,
  4650,
  1307,
  2520,
  3944,
  2837],
 [1172, 1172, 1064, 501, 3981, 1914, 11, 2375, 1183, 1078, 2978, 991],
 [1360, 2135, 1808, 4686, 4130, 4468, 1274, 1143, 1362, 3541, 721],
 [4490, 1847, 3428, 2678, 2294, 366, 2207, 4130, 1229, 1229, 1362, 3541, 721],
 [2637, 2865, 2961, 710, 2191, 1870, 2294, 4022, 1362, 3541, 721],
 [2842, 3426, 2614, 2820, 4464, 4432, 848, 811, 2294, 2132],
 [4659, 579, 4275, 2690, 4713, 3400, 3876, 2283],
 [457, 4606, 1866, 4477, 1602, 2583, 3345, 4848, 3373, 1882, 4958],
 [2054, 4568, 384, 4432, 2294, 2191],
 [1389, 1851, 3425, 2533, 780, 1952, 4958, 2153, 3461],
 [4888, 1977, 2764, 4308, 4164, 4959, 1651, 1362, 3541, 721],
 [4853, 2116, 2605, 3626, 1963, 1362, 3541, 721],
 [4579, 1839, 789, 1155, 1990, 3453, 726, 4231, 4644, 469],
 [3430, 1398, 401],
 [4097, 2113, 561, 2678, 2294, 3646, 1300, 2837],
 [3115,
  3750,
  3532,
  4317,
  1230,
  2901,
  3731,
  3723,
  4246,
  4164,
  1362,
  2533,
  4468],
 [2516, 2307, 3380, 4060, 4209, 1483, 833, 1604, 4214],
 [1172, 2928, 2294, 3258, 2543, 2837],
 [725, 772, 702, 4535, 2929, 4312, 4959, 4776, 1312, 4130, 4210, 1785],
 [4494, 3861, 4765, 3723, 306, 833, 4832, 3432, 4988, 1362, 3541, 721],
 [4060, 4456, 4272, 957, 2683, 4958, 1881],
 [2520, 1407, 650, 3914, 2307, 594, 4119, 2332, 262, 3226, 2293, 2837],
 [1774, 401, 4576, 664, 1474, 3630, 383, 2714],
 [2773, 2282, 2223, 3115, 1772, 665, 4060, 1915, 4461, 1362, 3541, 721],
 [401, 3380, 2541, 2190, 1362, 3541, 721],
 [4097, 2113, 561, 797, 95, 4312, 3115, 2837],
 [4398,
  2612,
  1857,
  2898,
  1938,
  1750,
  758,
  341,
  1852,
  2684,
  1263,
  4398,
  2612,
  1857,
  2898,
  1938,
  1750,
  758],
 [3993, 1362, 2117, 3828, 4724, 1362, 3541, 721],
 [4311, 4958, 1265, 1765, 4673, 4235, 54, 4948, 618, 1362, 3541, 721],
 [4175, 1671, 3873, 2332, 4186, 3278, 2152, 4256, 1911, 1362, 3541, 721],
 [2191, 4811, 2683, 4708, 3604, 560, 1362, 3541, 721],
 [2119, 3514, 298, 304, 69],
 [1546, 448, 2883, 647],
 [4562, 3652, 2254, 2463, 634, 3019, 4961, 2837],
 [3569, 573, 3569, 1194, 1903, 4746, 1362, 3541, 721],
 [2502, 3076, 2604, 883, 3288, 1335, 2572, 2837],
 [3343, 3254, 3092, 1164],
 [2901, 1380, 3797, 1120, 66, 2057, 1362, 3541, 721],
 [2729, 3213, 1560, 3651, 3155, 1910, 1563, 4933],
 [4872, 4268, 2717, 372, 2842, 2311, 1784, 3186, 2837],
 [1161, 3981, 1177, 3233, 975, 2796, 2223, 1362, 3541, 721],
 [2964, 2268, 4987, 2756, 945, 1606, 826, 3608, 3944],
 [],
 [2546, 1790, 1118, 1990, 4542, 1362, 1642, 1362, 3541, 721],
 [2179, 2307, 625, 3451, 3561, 4658, 3622, 509, 373, 4701, 4066, 2837],
 [4942, 4276, 40],
 [2481, 4502, 2285, 4664, 2191, 4101],
 [2800, 2545, 568, 1197, 3587, 4291, 3326, 2401, 138, 2837]]

In [23]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [24]:
onehot_repr[1]

[728, 401, 3380, 1042, 2583, 3419, 2837]

### Embedding Representation

In [25]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)

[[4444 4285 4822 ...    0    0    0]
 [ 728  401 3380 ...    0    0    0]
 [4787 2360 3686 ...    0    0    0]
 ...
 [4942 4276   40 ...    0    0    0]
 [2481 4502 2285 ...    0    0    0]
 [2800 2545  568 ...    0    0    0]]

In [26]:
embedded_docs[1]

array([ 728,  401, 3380, 1042, 2583, 3419, 2837,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [27]:
embedded_docs[0]

array([4444, 4285, 4822, 4189,  384,  225, 2944, 1039, 3515,   79,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [28]:
## Creating model
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None

In [29]:
len(embedded_docs),y.shape

NameError: name 'y' is not defined

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

### Model Training

In [ ]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 4s 11ms/step - loss: 0.3495 - accuracy: 0.8247 - val_loss: 0.2056 - val_accuracy: 0.9114
Epoch 2/10
192/192 [==============================] - 2s 9ms/step - loss: 0.1464 - accuracy: 0.9429 - val_loss: 0.2070 - val_accuracy: 0.9104
Epoch 3/10
192/192 [==============================] - 2s 8ms/step - loss: 0.1037 - accuracy: 0.9635 - val_loss: 0.2376 - val_accuracy: 0.9125
Epoch 4/10
192/192 [==============================] - 2s 8ms/step - loss: 0.0699 - accuracy: 0.9758 - val_loss: 0.2565 - val_accuracy: 0.9183
Epoch 5/10
192/192 [==============================] - 2s 9ms/step - loss: 0.0547 - accuracy: 0.9801 - val_loss: 0.2616 - val_accuracy: 0.9075
Epoch 6/10
192/192 [==============================] - 2s 8ms/step - loss: 0.0456 - accuracy: 0.9839 - val_loss: 0.3549 - val_accuracy: 0.9127
Epoch 7/10
192/192 [==============================] - 2s 8ms/step - loss: 0.0319 - accuracy: 0.9891 - val_loss: 0.3948 - val_accuracy: 0.8998
Epoch 8/10
192/192 [==============================] - 2s 8ms/step - loss: 0.0286 - accuracy: 0.9904 - val_loss: 0.3906 - val_accuracy: 0.9072
Epoch 9/10
192/192 [==============================] - 2s 8ms/step - loss: 0.0217 - accuracy: 0.9923 - val_loss: 0.4145 - val_accuracy: 0.9054
Epoch 10/10
192/192 [==============================] - 2s 8ms/step - loss: 0.0224 - accuracy: 0.9918 - val_loss: 0.4555 - val_accuracy: 0.9036

### Adding Dropout

In [34]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

### Performance Metrics And Accuracy

1.   List item
2.   List item

In [35]:
y_pred=model.predict(X_test)

NameError: name 'X_test' is not defined

In [ ]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test,y_pred)

array([[3135,  284],
       [ 297, 2319]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.903728251864126

In [ ]:
from sklearn.metrics import classification_report

              precision    recall  f1-score   support

           0       0.91      0.92      0.92      3419
           1       0.89      0.89      0.89      2616

    accuracy                           0.90      6035
   macro avg       0.90      0.90      0.90      6035
weighted avg       0.90      0.90      0.90      6035